$(function(){
  $("#idheader").load("./header.html"); 
  $("#idheader1").load("./header1.html"); 
  $("#idheader2").load("./header2.html"); 
  $("#idheader3").load("./header3.html"); 
  $("#idfooter").load("./footer.html"); 
  $("#idfooter1").load("./footer1.html"); 
  $("#idfooter2").load("./footer2.html"); 
  $("#idfooter3").load("./footer3.html"); 
});