$(function(){
  $("#idheader").load("/header.html"); 
  $("#idheader1").load("/diegoMarquez/header1.html"); 
  $("#idheader2").load("/camilaNani/header2.html"); 
  $("#idheader3").load("/ianRebuffo/header3.html"); 
  $("#idfooter").load("/footer.html"); 
  $("#idfooter1").load("/diegoMarquez/footer1.html"); 
  $("#idfooter2").load("/camilaNani/footer2.html"); 
  $("#idfooter3").load("/ianRebuffo/footer3.html"); 
});